name: 'Ninja installer'
description: 'Greet someone'
runs:
  using: "composite"
  steps:
    - name: Install Ninja(windows)
      shell: bash
      if: ${{ runner.os == 'Windows' }}
      run: |
        choco install ninja

    - name: Install Ninja(Linux)
      shell: bash
      if: ${{ runner.os == 'Linux' }}
      run: |
        sudo apt-get install -y ninja-build

    - name: Install Ninja(macOS)
      shell: bash
      if: ${{ runner.os == 'macOS' }}
      run: |
        brew install ninja
